"""
Friction inversion with WLS-corrected MPM solver.

This script mirrors ``train.py`` exactly, substituting the WLS solver so that
pure quadratic B-spline + boundary correction is used throughout.

Key differences from ``train.py``:
* Uses ``build_solver_wls`` from ``jaxmpm.solver_wls``
* Default data path is ``data/ground_truth_trajectory_wls.npy``
  (generated by ``generate_data_wls.py``)
* Outputs go to ``results_wls/<run_name>/`` to avoid overwriting baseline results

Usage
-----
    # Step 1 – generate WLS ground truth (once)
    python generate_data_wls.py

    # Step 2 – run inversion
    python train_wls.py                        # 500 observed particles
    python train_wls.py --n_obs 100
    python train_wls.py --epochs 300 --lr 0.05

    # Cross-kernel test: train WLS model on the standard baseline data
    python train_wls.py --data data/ground_truth_trajectory.npy

Output
------
    results_wls/<run_name>/log.txt             – per-epoch loss & param log
    results_wls/<run_name>/epoch_*_params.npy  – saved parameter checkpoints
"""

import argparse
import os
import sys
import time

import jax
import jax.numpy as jnp
import numpy as np
import optax
from jax.flatten_util import ravel_pytree

jax.config.update("jax_enable_x64", True)

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))
from jaxmpm import MPMConfig, initialize_block_particles
from jaxmpm.solver_wls import build_solver_wls


# ======================================================================
# CLI
# ======================================================================
def parse_args():
    p = argparse.ArgumentParser(
        description="Dam-break friction inversion – WLS solver"
    )
    p.add_argument("--n_obs",       type=int,   default=500,
                   help="Number of randomly sampled observation particles")
    p.add_argument("--epochs",      type=int,   default=500,
                   help="Number of optimisation epochs")
    p.add_argument("--lr",          type=float, default=1e-1,
                   help="Initial Adam learning rate")
    p.add_argument("--decay_rate",  type=float, default=0.9,
                   help="Exponential LR decay factor per --decay_steps")
    p.add_argument("--decay_steps", type=int,   default=20,
                   help="LR decay interval (epochs)")
    p.add_argument("--seed",        type=int,   default=0,
                   help="RNG seed for particle sampling")
    p.add_argument("--data",        type=str,
                   default="data/ground_truth_trajectory_wls.npy",
                   help="Path to ground-truth trajectory (.npy)")
    return p.parse_args()


# ======================================================================
# Main
# ======================================================================
def main():
    args = parse_args()

    # ------------------------------------------------------------------
    # 1. Configuration (must match the data-generation script)
    # ------------------------------------------------------------------
    cfg = MPMConfig(
        domain_x=2.0, domain_y=0.4, n_grid_x=200,
        dt=3e-5, total_time=0.4,
        rho0=1000.0, c=35.0, gravity=9.8,
        particles_per_cell_axis=2,
        save_every=10, block_size=500,
    )

    x0, n_particles = initialize_block_particles(cfg, block_x=0.5, block_y=0.3)
    v0        = jnp.zeros((n_particles, 2))
    C0        = jnp.zeros((n_particles, 2, 2))
    rho0_arr  = jnp.ones(n_particles) * cfg.rho0
    pressure0 = jnp.zeros((n_particles, 2, 2))

    # ------------------------------------------------------------------
    # 2. Load ground-truth & sample observation indices
    # ------------------------------------------------------------------
    ground_truth = jnp.array(np.load(args.data))
    key     = jax.random.PRNGKey(args.seed)
    obs_idx = jax.random.choice(key, n_particles, (args.n_obs,), replace=False)
    print(f"Particles: {n_particles}  |  Observations: {args.n_obs}")
    print(f"Ground-truth file: {args.data}")

    # ------------------------------------------------------------------
    # 3. Build WLS-corrected differentiable solver
    # ------------------------------------------------------------------
    simulate_wls = build_solver_wls(cfg, n_particles)

    # ------------------------------------------------------------------
    # 4. Loss function
    # ------------------------------------------------------------------
    @jax.jit
    def loss_fn(params):
        sim_bands = params["friction_bands"]
        _, _, _, _, _, x_hist = simulate_wls(
            rho0_arr, v0, x0, C0, pressure0, sim_bands
        )
        diff = x_hist[1:, obs_idx] - ground_truth[1:x_hist.shape[0], obs_idx]
        err = jnp.sqrt(jnp.sum(jnp.square(diff), axis=-1) + 1e-20)
        return jnp.sum(jnp.sum(err, axis=1))

    # ------------------------------------------------------------------
    # 5. Optimiser (identical schedule to train.py for fair comparison)
    # ------------------------------------------------------------------
    schedule = optax.exponential_decay(
        init_value=args.lr,
        transition_steps=args.decay_steps,
        decay_rate=args.decay_rate,
    )
    optimiser = optax.adam(learning_rate=schedule)

    num_bands = 5
    params    = {"friction_bands": jnp.ones(num_bands - 1) * 0.2}
    opt_state = optimiser.init(params)

    # ------------------------------------------------------------------
    # 6. Output directory
    # ------------------------------------------------------------------
    run_name = f"wls_obs{args.n_obs}_lr{args.lr}"
    out_dir  = os.path.join("results_wls", run_name)
    os.makedirs(out_dir, exist_ok=True)
    log_path = os.path.join(out_dir, "log.txt")
    log_file = open(log_path, "w")

    def log(msg):
        print(msg)
        print(msg, file=log_file)
        log_file.flush()

    log(f"WLS solver  |  n_obs={args.n_obs}  lr={args.lr}  data={args.data}")
    log(f"{'Epoch':>6s}  {'Loss':>12s}  {'μ (softplus)':>40s}  {'Time':>8s}")
    log("-" * 80)

    # ------------------------------------------------------------------
    # 7. Training loop
    # ------------------------------------------------------------------
    for epoch in range(1, args.epochs + 1):
        t0 = time.time()
        loss, grads   = jax.value_and_grad(loss_fn)(params)
        updates, opt_state = optimiser.update(grads, opt_state)
        old_params = params
        params     = optax.apply_updates(params, updates)
        elapsed    = time.time() - t0

        mu_vals = jax.nn.softplus(old_params["friction_bands"])
        mu_str  = "  ".join(f"{v:.4f}" for v in mu_vals)
        log(f"{epoch:6d}  {loss:12.4e}  [{mu_str}]  {elapsed:7.1f}s")

        if epoch % 10 == 0:
            flat, _ = ravel_pytree(params)
            fpath = os.path.join(out_dir, f"epoch_{epoch:04d}_params.npy")
            np.save(fpath, np.array(flat))

    log_file.close()
    print(f"\nTraining finished.  Results saved to {out_dir}/")


if __name__ == "__main__":
    main()
